### ISSUE TITLE
Alert type stuck on info

### ISSUE THREAD

**Issue by brezuicabogdan** [mouse0270/bootstrap-notify#104]
Hi,

I seem to be missing something but afterreading all the issues on github and documentation I still havent found an answer.

My code is:
``` JavaScript
$.notify({
	icon: "fa fa-thumbs-o-down",
	title: "<strong>" +"Atentie! " + "</strong> ",
	message: "Campania nu este inactiva"
},{
	type: 'danger',
	placement: {
		from: "top",
		align: "center"
	},
	offset: 52,
	allow_dismiss: true,
	newest_on_top: true
});
```

and still the alerts are showing up as info

WHAT AM I MISSING?

Thank you.

**Comment by mouse0270** [comment]
This looks correct, would you be able to replicate this using jsfiddle.net or provide me with a demo. Everything looks coorect.

**Comment by brezuicabogdan** [comment]
Replicating this on jsfiddle is a little bit difficult because I wold have to replicate every css and js component I load and there are a lot of them. I tried to create a static page so that I can provide as an example but surprisingly it works just fine. This leads me to belive there is an incompatibility issue with some other component either js or css I load. I will try disabling them one by one to see wich one generates the issue.

Home I will find a solution and get back to you when I do 

Thank you very much,

**Comment by mouse0270** [comment]
Your best solution is to use debugger and see what csss styles are being applied to the notification. Thsi should help identify the issue.
