### ISSUE TITLE
Suggestion: Add direct download link to latest version files

### ISSUE THREAD

**Issue by roooodcastro** [mouse0270/bootstrap-notify#108]
The README currently only has instructions on how to install using either Bower or Meteor.

There should be a direct link to the .js files of the latest version. The way it is right now, some people may just grab the files from the main file listing, that lists files from the master branch, which can contain broken or experimental code.

It's not really a big issue, but may be a nuisance for lazy or inattentive people. Plus it's always easier to have the download together with the other install options.

**Comment by mouse0270** [comment]
So add a download that points to the last release which should be stable? I can add that.

**Comment by mouse0270** [comment]
Please let me know if the updated readme is what you were looking for. If so please close thise issue.

Thank you for your request.

**Comment by roooodcastro** [comment]
Yes, something pointing to the release files (for example: https://github.com/mouse0270/bootstrap-notify/blob/3.1.3/bootstrap-notify.min.js)

**Comment by mouse0270** [comment]
I just pointed it to the release not a direct file.

**Comment by roooodcastro** [comment]
I just saw it, it's better now, Github adds the direct download links at the bottom of the release page, which is nice. Thank you!

**Comment by mouse0270** [comment]
I also updated the release so it includes a download now file which download the whole release right at the top. This should help avoid people who may not know to scroll to the very bottom.
