### ISSUE TITLE
bootstrap-notify.remabledesigns.com doesn't work

### ISSUE THREAD

**Issue by avasenin** [mouse0270/bootstrap-notify#112]
It returns pageok all the time

**Comment by mouse0270** [comment]
haha, I guess when I switched servers this didn't carry over for some reason. I am at work now and wont be able to fix it until later today.

Thank you for bring this to my attention. It would have been like that for most of the weekend. haha

**Comment by vkbansal** [comment]
We are in a fix. Need the docs ASAP. Please try to fix it.

Thank you.

**Comment by avasenin** [comment]
@vkbansal I used cached google's copy (http://webcache.googleusercontent.com/search?q=cache:dwCCY5VvnM8J:bootstrap-growl.remabledesigns.com/+&cd=1&hl=en&ct=clnk&gl=ru)

**Comment by mouse0270** [comment]
Just checked this morning and the website appears to be back up. sorry for the down time and thank you for letting me know.

**Comment by vkbansal** [comment]
@mouse0270 Still unable to access it. Tried after clearing cache.

**Comment by mouse0270** [comment]
Are you using http://bootstrap-notify.remabledesigns.com/ or http://bootstrap-growl.remabledesigns.com/

**Comment by vkbansal** [comment]
@mouse0270 http://bootstrap-notify.remabledesigns.com/  isn't working but http://bootstrap-growl.remabledesigns.com/ is

**Comment by mouse0270** [comment]
That is odd. They actually point to the same folder... If one works the other should work too....

I can look into this, but could you do me a favor and check the site again in 24 hours. I don't want to close this issue until I am sure everything is resolved. I'll look into this more when I get home and see what I can do.

**Comment by vkbansal** [comment]
Sure no problem :+1:

**Comment by mouse0270** [comment]
let me know if you are still having an issue loading the site though the http://bootstrap-notify.remabledesigns.com/ url

**Comment by vkbansal** [comment]
Now it's working :)

**Comment by mouse0270** [comment]
Sweet!
