### ISSUE TITLE
Documentation and demo page not working

### ISSUE THREAD

**Issue by mfunaro** [mouse0270/bootstrap-notify#113]
When you visit the documentation/demo page the response only contains 'pageok'.

**Comment by mouse0270** [comment]
people keep reporthing this but I can't seem to figure out why? 

What url are you using:
http://bootstrap-notify.remabledesigns.com/
OR
http://bootstrap-growl.remabledesigns.com/

I had to switch hosting servers but it seems to be working for most people. I don't understand why though. It works for most people with either url. haha.

**Comment by mfunaro** [comment]
Ah, I guess I should have searched closed issues as well as open when I did my search prior to posting. 

Both of those links in your comment give me the same 'pageok' response in Chrome. It seems to be a browser specific, on my Chrome Version 45.0.2454.85 (64-bit), I get the 'pageok' response but I just tried in Firefox Version 40.0.3 and it works fine.

**Comment by mouse0270** [comment]
I just contacted my hosting company. If you clear the cache for that page it should work now for both domains.

**Comment by mfunaro** [comment]
I did an 'empty cache and hard reload' in Chrome and it didn't alleviate the issues. But at least I can use Firefox to view to docs.

**Comment by mouse0270** [comment]
Really starting to hate this new hosting!
