### ISSUE TITLE
Progress bar is always shown, except when delay is 0 (zero)

### ISSUE THREAD

**Issue by josefsj3m** [mouse0270/bootstrap-notify#117]
Hi, I am having the same problem with progress bar as related by andrel7 here. The progress bar is alwasy shown, even if I disable it. If delay is 0 (zero) the progress bar is not shown, removing showProgressbar:false does not work for me.   I am using version 3.1.3 and the following code:
```javascript
$.notify({
                    // options
                    title: name,
                    message: msg,
                    icon: 'fa fa-paw'
                },{
                    // settings
                    type: 'info',
                    newest_on_top: true,
                    delay: 5000,
                    showProgressbar: false,
                    placement: {
                        from: "top",
                        align: "center"
                    }
                });
```
I'd appreciate some help.

Thanks in advance,

Fernando.

**Comment by josefsj3m** [comment]
I am sorry, my fault. I was using version 3.0.0, when I upgrade to 3.1.3 the problem was solved.

Thanks,

Fernando

**Comment by mouse0270** [comment]
Yeah, I poorly tested version 3.0.0. There were a lot of bugs. Glad an update solved the problem.

**Comment by josefsj3m** [comment]
Thanks Robert. You've made an awesome plug-in.

-----Mensagem Original-----
De: "Robert McIntosh" <notifications@github.com>
Enviada em: ‎16/‎10/‎2015 21:26
Para: "mouse0270/bootstrap-notify" <bootstrap-notify@noreply.github.com>
Cc: "josefsj3m" <josefsmvm@gmail.com>
Assunto: Re: [bootstrap-notify] Progress bar is always shown, except whendelay is 0 (zero) (#117)

Yeah, I poorly tested version 3.0.0. There were a lot of bugs. Glad an update solved the problem.
