### ISSUE TITLE
All animations are not working

### ISSUE THREAD

**Issue by thiagoross** [mouse0270/bootstrap-notify#120]
Hi,

Man, I thought this plugin awesome! And I'm trying to make this work, but I don't know why... it's not working.

I installed using bower, I can show the notification, but none of the animations are working for me.

It's like, the notification just show up, and if a click on X button, it disappears, no animation at all.

I don't know if the problem is with the versions I'm using:
bootstrap-3.3.5
jquery-2.1.4

Any ideas what am I doing wrong?

**Comment by sandmanman** [comment]
@import animate.css
http://daneden.github.io/animate.css/

**Comment by thiagoross** [comment]
Thanks @sandmanman! I will try it

**Comment by YuriFontella** [comment]
Obrigado @sandmanman , deu certo!

**Comment by ekanur** [comment]
Thanks, you help me guys, didnt know why did this issue appear?

**Comment by SimonP06** [comment]
Thank @sandmanman

**Comment by SimonP06** [comment]
Thanks @sandmanman
