### ISSUE TITLE
Is IE9 supported in all versions ?

### ISSUE THREAD

**Issue by fabm22** [mouse0270/bootstrap-notify#124]
Hi, 

by testing the demo/doc page (http://bootstrap-notify.remabledesigns.com/) on a IE9 browser through browserstack, it doesn't seem to work. 

Is this because you might have the latest version on the demo webpage ?

Is IE 9 supposed to work with the latest version ?

Thanks a lot.

**Comment by mouse0270** [comment]
I think it wont work on my site because I use jQuery 2.1 instead of the other version that is more browser compatible.
