### ISSUE TITLE
Placement aligin center taking full width of screen in version 3.1.5

### ISSUE THREAD

**Issue by preetham1290** [mouse0270/bootstrap-notify#131]
$.notify({message: "Some message"},{type: 'success', placement: {
                        from: "top",
                        align: "center"
                    }
});
If i configure in this way with Bootstrap Notify 3.1.5 notification is taking full width of screen, but same code in Bootstrap Notify 3.1.3 is working properly

Note: I didn't check with 3.1.4

**Comment by mouse0270** [comment]
Please use the inspector on chrome or firefox and make sure the container has a bootstrap col. It is what I use to control the width.
