### ISSUE TITLE
update a tag to 1.3.5

### ISSUE THREAD

**Issue by maruilian11** [mouse0270/bootstrap-notify#132]
hi, would you please update the tags to the latest version so that we can add your lib to https://cdnjs.com **with git auto-update**.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6707

**Comment by mouse0270** [comment]
I honestly can't remember how to. I have to look up how to update the tags.

**Comment by maruilian11** [comment]
ok, take your time, please close this issue when you done it, thank you!

**Comment by maruilian11** [comment]
duplicate with https://github.com/mouse0270/bootstrap-notify/issues/127
