### ISSUE TITLE
Question: Indeterminate Progressbar

### ISSUE THREAD

**Issue by stimko68** [mouse0270/bootstrap-notify#155]
Is there a way to override the default behavior of the progressbar and show an indeterminate one instead? I'm trying to show an alert when I make an AJAX call and then update the alert on `success`. For example:

```javascript
var notify = $.notify('Saving...', {
    allow_dismiss: false,
    showProgressbar: true,
});

$.ajax({
    url: '/some/url',
    type: 'POST',
    data: {},
    success: function(data) {
        // Do some stuff here
        notify.update('showProgressbar', false);
        notify.update('type', 'success');
        notify.update('message', 'Settings saved successfully');
    },
    error: function(xhr) {
        // Do some stuff here
        notify.update('showProgressbar', false);
        notify.update('type', 'danger');
        notify.update('message', 'Error saving settings: ' + xhr.responseText);
    }
});
```

Basically while the page is waiting for the response from the server I want to show an indeterminate progressbar then hide it when I get the `success` or `error` callback. Is this currently possible? 

Second question: is it possible to dynamically update the progressbar's value instead of the library doing it automatically?

Thanks.

**Comment by mouse0270** [comment]
Setting delay to 0, so you have to manually close the alert once the progress bar is full should work.

**Comment by stimko68** [comment]
Thanks for the quick response! That works perfectly!

**Comment by mouse0270** [comment]
I use the same code for a project of mine. haha. It was easy to know off the top of my mind.
