### ISSUE TITLE
Programmatically close a notify

### ISSUE THREAD

**Issue by flightsurvey** [mouse0270/bootstrap-notify#160]
As the documentation website is down could anyone tell me if it is possible to programmatically close a notify that has been initiated with "delay: 0"?

The system we are using it in signs out after five minutes of inactivity and it's just possible that the user may have left a notify open.

**Comment by gs2810** [comment]
From the [documentation](http://bootstrap-notify.remabledesigns.com/#documentation):

> **Close**
> `var notify = $.notify('...'); `
> `notify.close();`

Disclaimer: Not a developer/maintainer, just a fan :)

**Comment by mouse0270** [comment]
@gs2810 perfect answer. I am working on getting to doc site back up. Sorry I am releasing a new CMS for my clients and I forgot that this was on the same sever. I am working really hard to get everything back up and running today.

**Comment by flightsurvey** [comment]
Many thanks

**Comment by mouse0270** [comment]
If this resolves your problem, please remember to return and close this issue.
