### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by gs2810** [mouse0270/bootstrap-notify#161]
Hello,

> Future home of something quite cool

Seems your website is down: http://bootstrap-notify.remabledesigns.com/

Currently can still access via Google Cache: http://webcache.googleusercontent.com/search?q=cache:qvKV1f4VrAcJ:bootstrap-notify.remabledesigns.com/+&cd=1&hl=pt-PT&ct=clnk&gl=pt

**Comment by mouse0270** [comment]
Yes, I am releasing a new CMS for my clients which are on the same server. I had to make several changes and forgot this was on the same server. I am working on getting it back up and running today. 

I am terrible sorry, so many things going on I forgot about this. :(

**Comment by ayazhussein** [comment]
Website still down :D

**Comment by mouse0270** [comment]
It is back up!
