### ISSUE TITLE
Make Bootstrap notify to be working

### ISSUE THREAD

**Issue by jt4000** [mouse0270/bootstrap-notify#171]
What part am I missing in order to make bootstrap notify to be working?

I just can't find the error.

jsbin.com/tagohopofo/edit?html,js,output

Thank you!

**Comment by mouse0270** [comment]
Wrong library.
https://cdnjs.com/libraries/mouse0270-bootstrap-notify

that's the one you're looking for. hope that helps.

**Comment by jt4000** [comment]
Thank you for your help!
