### ISSUE TITLE
How to make a notice with fade in and fade out

### ISSUE THREAD

**Issue by jt4000** [mouse0270/bootstrap-notify#173]
I would like to have fade in and fade out when this notice info will displace.

I still use the same source code but I still can't retrieve the fade in and face out effect.

What part am I missing in order to achieve it?

Thank you!

Same source code in jsfiddle and jsbin but it only work at jsbin.

https://jsfiddle.net/qenn83yg/

http://jsbin.com/cofigosute/edit?html,js,output

**Comment by mouse0270** [comment]
Custom CSS Not Included
My plugin relies on custom css for its intro and exit animations. For this I recommend using this wonderful resource called Animate.css by Daniel Eden. He has put together a wonderful set of css animations that work perfectly with this plugin.

**Comment by rinogo** [comment]
It looks like Animate.css has been updated. I couldn't get classes like `animated fadeInDown` (from the bootstrap-notify docs) to work. Instead try something like the following:

```
animate: {
	enter: "animate__animated animate__fadeInDown",
	exit: "animate__animated animate__fadeOutUp"
}
```
