### ISSUE TITLE
Mixed animations broken with animate.css

### ISSUE THREAD

**Issue by aleho** [mouse0270/bootstrap-notify#188]
Using animate.css a configuration like the following is broken. Exit animations just don't do what they're supposed to, in this example the notification just disappears after the animation duration.

```JS
animate: {
    enter: 'animated slideInRight',
    exit:  'animated fadeOutUp'
}
```

This is caused by a mixture of effects (slide, fade) which seem to conflict with each other.

**Comment by mouse0270** [comment]
Thanks, I will look into including your pull request. Good catch!
