### ISSUE TITLE
Modify alert width

### ISSUE THREAD

**Issue by austintoddj** [mouse0270/bootstrap-notify#194]
Is there a way to modify the width of default alerts? I thought it would be possible using the `template` option, but still can't seem to affect it. All I'd like to do is make the alert match the length of text included in it, or make it responsive at least.  Here's what the current alert looks like:

<img width="676" alt="screen shot 2018-03-09 at 10 03 36 pm" src="https://user-images.githubusercontent.com/8037011/37238216-6e4a12cc-23e7-11e8-9124-e5cef8fa306d.png">

And here is the notification script:

```js
$.notify({
            // options
            message: 'Success! Profile has been updated.'
        },{
            // settings
            type: 'success',
            allow_dismiss: false,
            delay: 2800,
            animate: {
                enter: 'animated fadeInDown',
                exit: 'animated fadeOutUp'
            },
        });
```

**Comment by paskyorg** [comment]
Try this:

`$.notifyDefaults({
    onShow: function() {
        this.css({'width':'auto','height':'auto'});
    },
});`

**Comment by mouse0270** [comment]
The width should be set via css using bootstrap classes `col-xs-11 col-sm-4`. If you remove those from the template you should be able to just specifiy the specific size using css such as

``` css
div[data-notify="container"] { 
    width: auto; 
}```

**Comment by austintoddj** [comment]
Thanks for the help @mouse0270  @paskyorg, works great!

**Comment by Prajwal100** [comment]
> ```js
> type: 'success',
>             allow_dismiss: false,
>             delay: 2800,
>             animate: {
>                 enter: 'animated fadeInDown',
>                 exit: 'animated fadeOutUp'
>             },
>             onShow: function() {
>                 this.css({'width':'auto','height':'auto'});
>             },
> ```

thank you
