### ISSUE TITLE
animate.css added still animation not working

### ISSUE THREAD

**Issue by itsmekps** [mouse0270/bootstrap-notify#199]
animate.css already added but still animations are not working
help pls
Bootstrap v3.3.7
jQuery v2.1.4

**Comment by rinogo** [comment]
It looks like Animate.css has been updated. I couldn't get classes like `animated fadeInDown` (from the bootstrap-notify docs) to work. Instead try something like the following:

```
animate: {
	enter: "animate__animated animate__fadeInDown",
	exit: "animate__animated animate__fadeOutUp"
}
```
