### ISSUE TITLE
The official typings don't support the notify.update({'type': 'success', ... }) method

### ISSUE THREAD

**Issue by iivmok** [mouse0270/bootstrap-notify#202]
The example in the documentation at http://bootstrap-notify.remabledesigns.com/

```javascript
var notify = $.notify('<strong>Saving</strong> Do not close this page...', {
	allow_dismiss: false,
	showProgressbar: true
});

setTimeout(function() {
	notify.update({'type': 'success', 'message': '<strong>Success</strong> Your page has been saved!', 'progress': 25});
}, 4500);
```

Does not compile under TypeScript with latest typings. It seems to be a problem with the `INotifyReturn.update()` type definition. Would you like for me to make a pull request?

**Comment by mouse0270** [comment]
You would have to make a pull request. I did not make the initial TypeScript.
