### ISSUE TITLE
Set delay for growl auto close and time for show up

### ISSUE THREAD

**Issue by reypm** [mouse0270/bootstrap-notify#26]
This is more a question than a issue. I made this code to show the Growl message:

```
$.growl({
    message: "Some text"
}, {
    type: "danger",
    delay: 8000,
    allow_dismiss: true,
    animate: {
        enter: 'animated bounceInDown',
        exit: 'animated bounceOutUp'
    }
});
```

But,
- The message shows after long time
- The message appears for a few seconds

Maybe I misunderstood the docs but what I want is to let the message at least for 8 seconds, how I do that?

**Comment by mouse0270** [comment]
I haven't been able to duplicate this issue.
