### ISSUE TITLE
event not defined

### ISSUE THREAD

**Issue by rocketapi** [mouse0270/bootstrap-notify#28]
Bug found in the onShow and onHide callback settings.

Lines 159 and 265.
there is no event object available to pass thru to the settings.onShow and onHide methods.
These are being called manually whereas the onShown and onHidden will have an event object supplied by the event binding for the end of animation.

I propose the following fixes as the easiest way to resolve this:

line 159
settings.onShow(jQuery.Event("show"));

line 265
settings.onHide(jQuery.Event("hide"));

There may also be another way, and that would be to fire the onhide and onshow events on the animation start (lines 181 and 276)

Thanks,

John

**Comment by SentiQ** [comment]
Any update on this? Want to fire a function on Closing a growl. 
At the Moment onHide and onHidden are fired before the growl is shown.

**Comment by mouse0270** [comment]
I am releasing a new update at the end of this month. The update will have much better support for the event handlers and should resolve the firefox bug.

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this should be fixed. If it isn't please re-open this case. It seemed to be resolved in my testing though.
