### ISSUE TITLE
Smooth animation after notification exits

### ISSUE THREAD

**Issue by paulopmx** [mouse0270/bootstrap-notify#35]
Hi, in your demo it shows that when a notification exits, the next one will smoothly animate up to the top.

When I try to implement it on my project it does not animate smoothly as seen here: 

http://cl.ly/image/330h432Z2u3O

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this should be fixed. If it isn't please re-open this case. It seemed to be resolved in my testing though.
