### ISSUE TITLE
Center-aligned growl is not responsive with screen resize

### ISSUE THREAD

**Issue by iscribble** [mouse0270/bootstrap-notify#37]
**To Duplicate:**
* Navigate to bootstrap-growl.remabledesigns.com
* "Create Growl" with extended delay and set to the center of the screen
* Decrease window size, down to mobile width (for example)
* Growl may extend off the screen or appear not centered

See example Screenshot: http://i.imgur.com/sbqxbVa.png

**Seems obscure, what is the use-case?**
For us, the issue comes up with rotation on mobile devices. For example, if the user triggers the growl in landscape and then rotates to portrait, a situation much like the above screenshot can occur.

**What's the fix?**
We've got a window resize listener to re-set the growl's margin-left at *-($growl.outerWidth() / 2) + 'px'* and it seems to work just fine... but maybe there is another, more robust solution?

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this should be fixed. If it isn't please re-open this case. It seemed to be resolved in my testing though.
