### ISSUE TITLE
Include bootstrap [col-xs-11 col-sm-3] into the default template

### ISSUE THREAD

**Issue by serjrd** [mouse0270/bootstrap-notify#38]
Hi, thanks for your awesome project.

It took me some time to realize why the notification on my page look worse than those that you have on your demo page. By default the notifications lack some indentation from the 'x' close button.

On your demo page you set up a template to use [col-xs-11 col-sm-3] css classes that are not present in the sources.

Since notifications do look better with those classes present, and since you basically expect your own results to resemble the demo page, I suggest changing the default template.

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this should be fixed. If it isn't please re-open this case. It seemed to be resolved in my testing though.
