### ISSUE TITLE
onHide asks for non-existent event

### ISSUE THREAD

**Issue by jmuxfeldt** [mouse0270/bootstrap-notify#54]
you either need to provide an event for onHide, or you need to remove the event argument:
line 262 of bootstrap-growl.js
` if (settings.onHide) {
                settings.onHide(event);
            }
`

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this should be fixed. If it isn't please re-open this case. It seemed to be resolved in my testing though.
