### ISSUE TITLE
Not compatible with Glyphicons PRO fonts v1.9

### ISSUE THREAD

**Issue by toxsid** [mouse0270/bootstrap-notify#56]
I recently installed the new font package from: http://glyphicons.com/
They change their classes from:
example: ".glyphicons .leaf" to ".glyphicons .glyphicons-leaf"

My bootstrap growl alerts now loop the fade in animation. 

Not sure how the conflict is happening since there is no js errors in the console. Maybe you might have perspective on what may be causing this.

Thank you.
Here is my source code:
http://i.imgur.com/F98Ui15.png

Here is a video of it happening:
https://www.youtube.com/watch?v=SFfVCXZrNP8&list=UUmZJZ53ymIhqMZO4sT8U90Q

**Comment by mouse0270** [comment]
Thank you! I was able to test this by just creating a class called `animated` and setting `animation-iteration-count` to `infinite`

This is fixed as of version 3.1.3
