### ISSUE TITLE
add id after growl has been created

### ISSUE THREAD

**Issue by LDSign** [mouse0270/bootstrap-notify#57]
Hi

How can I access the growl object after it has been created? I would like to add an id to the growl container. Unfortunaley this does not work:

var growl = $.growl({...},{...});

growl.attr('id','test');

Thanks,
Frank

**Comment by mouse0270** [comment]
I would recommend either using the template as you did or use the onOpen function to assign a id and then when recalling your function that would generate the notification check to see if the id exists first.
