### ISSUE TITLE
please add an option to integrate a progressbar for dismiss-delay

### ISSUE THREAD

**Issue by lubberscorrado** [mouse0270/bootstrap-notify#59]
It would be nice to have a progress bar (either a tiny little bar at the top/bottom (just like youtube but only inside a growl-container) of each notification container or as a filler for the whole growl-container-background)
This way i can see when the growl container actually gets hidden.

**Comment by mouse0270** [comment]
This would be interesting. I am currently working on an update for this plugin that I expect to release by the end of the month. I'll see if I can get this in before I release.

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this has been added.
