### ISSUE TITLE
Use UMD for module wrapping allowing use in amd/browserify

### ISSUE THREAD

**Issue by pgilad** [mouse0270/bootstrap-notify#60]

**Comment by mouse0270** [comment]
Could you provide more information, I am not sure what you are asking?

**Comment by pgilad** [comment]
See:
https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

That will enable both commonJS and AMD module loaders to consume this package

**Comment by pgilad** [comment]
Can I submit a PR? @mouse0270

**Comment by mouse0270** [comment]
Of course, it'll take me some time to review it due to updates I am working on.

—

**Comment by pgilad** [comment]
from which branch should it originate? master or the beta3 branch?

**Comment by mouse0270** [comment]
Beta3 isn't quite finished yet. but I would recommend it since I hope to release it within the next few weeks.

**Comment by pgilad** [comment]
@mouse0270 any news on merging the PR?

**Comment by mouse0270** [comment]
@pgilad This has been included in version 3.0.0 I was trying to avoid updating 2.0.1 as much as possible.
