### ISSUE TITLE
i vote for Bootstrap Notification

### ISSUE THREAD

**Issue by lubberscorrado** [mouse0270/bootstrap-notify#65]
There already exists notify.js which could get confusing (maybe with cdn also) aswell, so

Bootstrap Notification

makes more sense to me and is clear. :)

btw: Awesome work you did and looking forward to V3  :)

**Comment by mouse0270** [comment]
Thank you, however I decided to go with Bootstrap Notify I liked the ring of it a lot more. And notification was kinda long.
