### ISSUE TITLE
URL click not working on IE9 / IE10

### ISSUE THREAD

**Issue by inboxzero** [mouse0270/bootstrap-notify#66]
We have this issue with our project and it is repeatable with the examples on the documentation page.

http://bootstrap-growl.remabledesigns.com/#growl-documentation
On the "passing a URL" example.

click the "create growl" button.
In IE9 / IE10 it works if you don't click on the text.  Nothing happens if you click on the text.

In IE11 and latest Chrome and Firefox, clicking on the text also loads the url.

**Comment by mouse0270** [comment]
This is a problem with IE9/10 not liking empty absolute anchor tags. The best way I found to fix this is to add an invisible image that stretches over the anchor tag. This is included in version 3.0.0 which will be released this weekend.

**Comment by inboxzero** [comment]
Thanks for the swift reply.  In the meantime, I have just made the message I'm displaying an anchor message and it now works.  
I'll revisit it, once 3.0.0 is released.

**Comment by mouse0270** [comment]
Version 3.0.0 has been released and this should be fixed. If it isn't please re-open this case. It seemed to be resolved in my testing though.
