### ISSUE TITLE
Missing Version Tags

### ISSUE THREAD

**Issue by josephspens** [mouse0270/bootstrap-notify#67]
My company was using v2.0.1 in production, via Bower, and this morning all our builds broke because that tag no longer existed.

Did the tag get removed this morning during the v3 bump? If so, why?

**Comment by mouse0270** [comment]
It shouldn't have, but it might have, see I am not familiar with bower nor how to really update it. let me take a look and see what I can do.

**Comment by josephspens** [comment]
I'm downgrading our version to 2.0.0, which should solve my immediate concern.

**Comment by mouse0270** [comment]
Okay, so I just realized that I did end up deleting the 2.0.1 tag, this was my mistake and I didnt mean to do it. I have added the old tag back and re-attached the files to this tag... Can you verify if this is working now? Like I said, I don't use bower, so I am not sure how it works.

**Comment by josephspens** [comment]
It works! Awesome, thanks.

**Comment by mouse0270** [comment]
Really sorry about that. I might have to spend some time this weekend learning bower. I really want to avoid breaking peoples sites.

Once again I am really sorry and I hope that you take a look at the new version it has slightly better support for IE browsers and can display a progress bar.
