### ISSUE TITLE
growl => notify

### ISSUE THREAD

**Issue by layanto** [mouse0270/bootstrap-notify#68]
Did you do search replace growl => notify in http://bootstrap-growl.remabledesigns.com/? For example ifightcrime's bootstrap growl also became bootstrap notify and the link does not work. 

Also maybe related to this rename or maybe bower.io search not working, but the only bootstrap.notify I found refers to another project. But bootstrap.growl still points correctly to your project in bower.io.

**Comment by mouse0270** [comment]
As for the first one find replace yes I did, but I thought I went back and corrected them all... I'll have to do that fix that in the morning.

As for the bower.io issue, in all honesty I know nothing about it I did what I have done for the past updates in hopes it would show up there. If you are someone you know would be willing to help me I would greatly appreciate it.

**Comment by layanto** [comment]
Don't know enough about bower registration. But doing a quick search both bootstrap-notify (github.com/goodybag/bootstrap-notify) and bootstrap.notify (github.com/Nijikokun/bootstrap-notify.git) already taken.

**Comment by mouse0270** [comment]
Please refer to case #69 It helps to resolve this issue.

**Comment by layanto** [comment]
http://bootstrap-notify.remabledesigns.com/ still have a few incorrect growl=>notify instances.

**Comment by mouse0270** [comment]
Can you re-open this?



—

**Comment by layanto** [comment]
Can't. As I didn't close the issue, I can't reopen it. See http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by mouse0270** [comment]
My bad, didn't realize that...
