### ISSUE TITLE
Bower naming issue

### ISSUE THREAD

**Issue by mstnorris** [mouse0270/bootstrap-notify#69]
In your readme you suggest to run `bower install bootstrap.notify` however this package is incorrect.

Instead it should be `bower install remarkable-bootstrap-growl` and then it works absolutely fine :)

**Comment by mouse0270** [comment]
Thank you very much for figuring this our. I have updated the readme.md to resolve this issue. I guess I really need to learn more about bower because I would really like it to read ```bower install remarkable-bootstrap-notify```

**Comment by layanto** [comment]
bower install bootstrap-growl also works. If you prefer remarkable-bootstrap-notify I can register that in bower.

**Comment by mouse0270** [comment]
Could you please do that for me. I would highly appreciate it.

**Comment by layanto** [comment]
Done. Just tested and confirmed working.

Use bower install remarkable-bootstrap-notify

**Comment by mouse0270** [comment]
One of the main reasons I love github is everyone is so helpful in my shortcomings.

Thank you very much for doing this for me.
