### ISSUE TITLE
update method api

### ISSUE THREAD

**Issue by layanto** [mouse0270/bootstrap-notify#71]
From the documentation, api for update method is only modifying one parameter at a time eg notify.update("title", "new title"); To modify/update multiple parameters, we need to call update method multiple times. 
Can I propose update api similar to the $.notify() api where multiple parameters can be modified at the same time?
Eg notify.update ({ icon: "fa fa-warning", title: "new title", message: "new message" });

**Comment by mouse0270** [comment]
I can look into this over the weekend. Off the top of my head I have an idea that might work, but wont know until I try it.

**Comment by mouse0270** [comment]
This has been included in version 3.0.1+
