### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by WebDevTmas** [mouse0270/bootstrap-notify#73]
Please remove the jquery and bootstrap requirements as those are non existing packages without a vendor. Unless I'm doing something wrong?

Also on packagist the name bootstrap-growl is still in use.

**Comment by mouse0270** [comment]
In all honesty I havent done anything other than add this file to github. Others have put together the composer/bower/etc features.

If you know someone or are able to do this I would greatly appreciate it.

**Comment by WebDevTmas** [comment]
I'll adjust it and create a pull request tonight (depending on what timezone you live in :D )

**Comment by WebDevTmas** [comment]
#74 opened pull request
