### ISSUE TITLE
setting delay to a value and setting timer to 0 causes the notification to never dissappear

### ISSUE THREAD

**Issue by Zxurian** [mouse0270/bootstrap-notify#75]
```
$.notifyDefaults({
    delay: 2000,
    timer: 0
})

$.notify({
    message: 'foobar'
});
```

the notification will stay on screen forever.

**Comment by mouse0270** [comment]
Timer can not be 0.

This variable only exists to remove time from the delay, this way you can  pause the delay on hover. To formaula looks like

```
timeLeft = delay - timer
```

and this is used with setInterval with the same amount of the timer variable.


May I ask why you set timer to 0?

**Comment by Zxurian** [comment]
ah, if the closing is based off the timer, that would explain it. As far as why, #76 explains my reasoning behind it. I'll close this since it's working as you intended.
