### ISSUE TITLE
Forked and published to NPM

### ISSUE THREAD

**Issue by seanTsmith** [mouse0270/bootstrap-notify#77]
FYI ... feel free to take it over not sure if I broke protocol - I just use npm front end and back end packaging.

**Comment by mouse0270** [comment]
For something like this it would be best to just make a pull-request.

**Comment by seanTsmith** [comment]
I've actually never done that.  If you want me to I will if its not too late.

**Comment by mouse0270** [comment]
It is honestly up to you. It isn't to late. I'll be looking at fixes, updates and pull request this weekend when I get a break.

So if you get the pull request in by then I'll make sure to merge it assuming their are not any problems.
