### ISSUE TITLE
Not available for meteor

### ISSUE THREAD

**Issue by sonyl** [mouse0270/bootstrap-notify#78]
Hi,
I tried to install your package with meteor, but got the following error:
>meteor add mouse0270:bootstrap-notify
 >=> Errors while parsing arguments:           
 >                                             
>While adding package mouse0270:bootstrap-notify:
>error: no such package

Even a search at atmospherejs.com showed no hits. The only thing I found was the outdated "zimme:bootstrap-growl" package.

**Comment by zimme** [comment]
I made a PR before to integrate meteor with this package but I was the old approach which forces the maintainer to manually publish each new version to meteor.

I have and still am gonna submit a new PR for this package which is gonna use the new [autopublish](http://autopublish.meteor.com/howitworks) method which @mouse0270 only needs to do a one-time setup and everytime a new release is pushed to this repository [autopublish.meteor.com](http://autopublish.meteor.com) will take care of publishing the new version to atmosphere.

I just haven't had the time to do the changes yet.

**Comment by zimme** [comment]
I've created an update PR for better Meteor integration. #85

**Comment by mouse0270** [comment]
Added to meteor, version 3.0.2 and 3.1.3
