### ISSUE TITLE
Progress bar is annoying and uncontrollable

### ISSUE THREAD

**Issue by mohghaderi** [mouse0270/bootstrap-notify#80]
Default settings for v3.0 has progress bar on all delayed messages that is super annoying for the users. There should be a setting to show this progress bar and by default it shouldn't be shown.
{
     showProgressbar: false
}

**Comment by mouse0270** [comment]
Added the feature and will upload 3.0.1 in the next few hours.

**Comment by mouse0270** [comment]
Included in 3.0.1
