### ISSUE TITLE
Progressbar should be programmable

### ISSUE THREAD

**Issue by mohghaderi** [mouse0270/bootstrap-notify#81]
it was good, if the progress bar was manageable inside the code like notify.progress = 90; It's simple through the template, but I wish it was a built-in feature.

**Comment by mouse0270** [comment]
Odd question, does this mean you would like to override the delay counter or that you want it to recalculate the delay based off the percentage you use. Or if you use notify.update({ 'progress':90}) it would disable the delay and the notification would need to be manually or programmatically closed.

**Comment by mouse0270** [comment]
Included in 3.0.1

**Comment by mohghaderi** [comment]
I wanted to use it for fileupload progress, and now it works perfectly. I don't know how to thank you. I just can say thank you so much.

**Comment by mouse0270** [comment]
No problem. If you come up with anything else, just ask and I'll see what I can do.
