### ISSUE TITLE
Solution for Glyphicons Pro Users

### ISSUE THREAD

**Issue by stevetruckstuff** [mouse0270/bootstrap-notify#87]
Hi-
The animation problem for users of Glyphicons Pro referenced in Issue #56 is a conflict between Glyphicons Pro and Eden's Animate.css package.  Both of these packages use the CSS class `animated` to apply some basic styles.  In the case of Glyphicons Pro, they explicitly set the `animation-iteration-count` property to `infinite` so the animations will repeat, whereas Animate.css uses the separate `infinite` class to accomplish this.  The animations loop as seen in the video posted on Issue #56 because the `animation-iteration-count` property is set to `infinite` by the Glyphicons Pro stylesheet.

Solutions would include anything that sets the `animation-iteration-count` property to `1` for bootstrap notifications.  This could be accomplished by adding another class to animated notifications, e.g.:
```css
body .animate-once {
    -webkit-animation-iteration-count: 1;
    animation-iteration-count: 1;
}
```

```javascript
$.notify('foo', { animate: { enter: 'animated fadeInRight animate-once' } });
```
From the perspective of Bootstrap Notify, the solution should probably be to add an inline style for this property to the `.alert` div.

Hope this helps other users!

UPDATE: Lest any Glyphicons Pro users think they are going crazy, I talked to the Glyphicons dev and he confirmed that animated icons is a feature that exists, though it's "more of an Easter egg and totally undocumented." :-)

**Comment by mouse0270** [comment]
If I made a small change and asked you to test it would you be able to. I do not have Glyphicons Pro.

**Comment by stevetruckstuff** [comment]
Sure.  Though my git-foo isn't very good, so it might take me a bit to get
latest.

Steve

**Comment by mouse0270** [comment]
Thank you! I was able to test this by just creating a class called `animated` and setting `animation-iteration-count` to `infinite`

This is fixed as of version 3.1.3

**Comment by stevetruckstuff** [comment]
Confirmed fixed.  Thanks for the quick fix!

Don't forget to update your home page too. ;-)

**Comment by mouse0270** [comment]
Is it not updated?

**Comment by stevetruckstuff** [comment]
Version got updated in the title, but there is still the text blurb about glyphicons pro under the *Using a Font Icon* section.

**Comment by mouse0270** [comment]
Good catch, I forgot about the blurb. haha
