### ISSUE TITLE
dismiss (close) icon isn't correctly positioned if not using url option

### ISSUE THREAD

**Issue by pgilad** [mouse0270/bootstrap-notify#92]

**Comment by mouse0270** [comment]
Can you provide me with an example of your call to Bootstrap Notify?

**Comment by pgilad** [comment]
Found the issue... it is caused by this check:
https://github.com/mouse0270/bootstrap-notify/blob/master/bootstrap-notify.js#L100-L102

Notice that `styleURL` also styles the dismiss icon. That code needs to be extracted to it's own function.

**Comment by mouse0270** [comment]
What are you passing as a URL? just an empty space? such as `""`

**Comment by mouse0270** [comment]
I see your point though. I'll look into correcting this on the upcoming weekend.

**Comment by pgilad** [comment]
It's an easy correction, can I PR?

**Comment by mouse0270** [comment]
If you would like. I would really appreciate it.

**Comment by pgilad** [comment]
Btw a blank string will resolve to a `#` as well (https://github.com/mouse0270/bootstrap-notify/blob/master/bootstrap-notify.js#L66)

**Comment by mouse0270** [comment]
Yeah, I know. It is why I was curious what you were doing to incite the issue. In the months I have released this I have yet to see this issue occur. haha

**Comment by pgilad** [comment]
Yeah I was going mad as to why in the examples it is (mostly) aligning the dismiss icon, and in our project it doesn't... Had to trace this in :cry:

**Comment by mouse0270** [comment]
Haha, gotta love that. I keep wanting to switch to use the actual bootstrap `alert-dismissal` class but haven't found a solution to the absolute position issue caused by the anchor tag.
