### ISSUE TITLE
Update latest version to npm (latest published is 3.0.0)

### ISSUE THREAD

**Issue by pgilad** [mouse0270/bootstrap-notify#94]

**Comment by mouse0270** [comment]
This is on my list of things to do. I recently purchased a property and have been spending alot of my free time working on it. I am sorry for the delay.

**Comment by pgilad** [comment]
No problem. You can add me as a collaborator in NPM, I'll take care of it

**Comment by mouse0270** [comment]
Assuming your username is the same on both GitHub and npm. I have added you.

Thank you very much for offering to do this. I really do appreciate it.

**Comment by pgilad** [comment]
Thanks... Can you add me as a collaborator to this repository so I can update the package.json version?
Also - what is the `dist` version directory for?

**Comment by mouse0270** [comment]
Please make a pull request for the updated package.json file.

As for the folder: I can't remember why it was created, it could probably be removed in the next update. haha.

**Comment by pgilad** [comment]
Published 3.1.3
