### ISSUE TITLE
Notify not showing on keydown

### ISSUE THREAD

**Issue by wroughtec** [mouse0270/bootstrap-notify#95]
I have a search form that uses ajax to pull in the data and I have disabled the enter key but rather than nothing occuring I wish to setup a notify however when I do so the message does not display unless I scroll.

````
$('#search').keydown(function(event) {
	if(event.keyCode == 13) {
		$.notify({
			// options
			message: 'message'
		},{
			// settings
			type: 'warning'
		});
	    event.preventDefault();
	    return false;
	}
});
````
Is this something I am doing wrong or is this not possible?

**Comment by mouse0270** [comment]
This seems to be working for me: http://jsfiddle.net/2s760cp0/1/

**Comment by wroughtec** [comment]
Weird something must be clashing my end thanks anyway

**Comment by mouse0270** [comment]
I would try using `.on("keyup", function(event) { ... }` instead of `.keyup(function(event) { .. } ` since that is really the only change I made. haha.

If you share a demo URL I might be able to better assist you. If you believe the issue is on your end, please close this issue.

**Comment by wroughtec** [comment]
It was not a js problem it was a change in the animation css file as I have stuff hidden that is faded in so the hidden on the animated class was not being removed until it becomes visible :+1:
